### ISSUE TITLE
newentry, selfentry commands are not working

### ISSUE THREAD

**Issue by githubuser9022** [mat-1/Repldex#80] opened 2021-01-08 20:22 UTC

**Comment by jetstream0** [comment] 2021-01-08 20:24
Hmm.. I think newentry works

**Comment by jetstream0** [comment] 2021-01-08 20:24
You can set a self entry but it does not show up when you do `^selfentry`

**Comment by IreTheKID** [comment] 2021-01-08 20:25
These commands are working as intended, I just used them right now.

**Comment by jetstream0** [comment] 2021-01-08 21:37
![image](https://user-images.githubusercontent.com/49297268/104066665-a4759880-51b6-11eb-945d-6c641a3cf1f7.png)
doesn;t look like it @IreTheKID

**Comment by githubuser9022** [comment] 2021-01-09 02:19
hmms

**Comment by leon332157** [comment] 2021-01-10 06:28
fixed with the latest version

**Closed by leon332157** 2021-01-10 06:28 UTC
